### ISSUE TITLE
Error in numeric value and decimal? property

### ISSUE THREAD

**Issue by luizfbicalho** [linmasaki/Kendo.DynamicLinqCore#13]
I'm posting this json 

`{
  "skip": 0,
  "take": 20,
  "filter": {
    "logic": "and",
    "filters": [
      {
        "field": "Value",
        "value": 207.81,
        "operator": "eq"
      },
      {
        "field": "Status",
        "value": 3,
        "operator": "eq"
      }
    ]
  }
}`

and my class is this

`public class Document
    {
        
        public decimal? Value{ get; set; }
        public DocumentStatus Status { get; set; }
    }`

and i'm getting this error

Operator '=' incompatible with operand types 'Decimal?' and 'Double'

what can be done to solve this?

**Comment by linmasaki** [comment]
Hmm…, I found the issue too. I will fix it as soon as possible, thanks for your report.



**P.S. A workaround I can provide that you can treat the property as "string" in kendo's model schema like below:**
``` javascript
dataSource: 
{
    schema:
    {
        ..... other settings.....
        model: 
        {
            id: "Id",            
            fields: {
                Id: { type: "number" },
                Price: { type: "number" }   // change "number" to "string"
            }
        },               
        ..... other settings.....
```

**Comment by linmasaki** [comment]
To upgrade the package to version v3.1.1, and try if it can work or not. Thanks!

**Comment by luizfbicalho** [comment]
thanks, i'll try it
