### ISSUE TITLE
IgnoreCase when getting property (Support camelCase)

### ISSUE THREAD

**Issue by Discofunk** [linmasaki/Kendo.DynamicLinqCore#14]
camelCase is often used for properties on client side (javascript/typescript) where as .NET it is common to use PascalCase.

This results in a mismatch and is causing an exception for me when Filter.GetLastPropertyType tries to find the matching property.

Allow support to ignore case would resolve this issue:

    PropertyInfo property = currentType.GetProperty(propertyName, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);

Or perhaps allowing users to set an option to IgnoreCase.

**Comment by linmasaki** [comment]
Could you give me a sample of this issue?

**Comment by linmasaki** [comment]
Since there has been no reply for a long time, so this issue is close.

**Comment by linmasaki** [comment]
Duplicate of #18, see its [details](https://github.com/linmasaki/Kendo.DynamicLinqCore/issues/18#issuecomment-788745060).
