### ISSUE TITLE
It just doesn't work as intended

### ISSUE THREAD

**Issue by SoapyMan** [linmasaki/Kendo.DynamicLinqCore#18]
Since change from 2.2.0 to 3.x things stopped worked properly, like
- value conversion from JSON ValueKind to simple types
- case insensitive field lookups in filter
- broken Enum support
- broken String filtering (getting message like `No applicable method 'Contains' exists in type 'String' (at index 24)`)
- overall failing to compile the expressions if **any** filter is specified

I've tried to fix it by myself but due to my lack of knowledge for dynamic expression generator I think devs should be notified too.

**Comment by linmasaki** [comment]
Please reference the prerequisites section of the readme file that may help you solve your issues, except point 2.

**Comment by SoapyMan** [comment]
Thank you for quick response!
Number 5 is actually this sadly https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client

And I got a fix for point 2, if you need:
```cs
// Filter.cs, GetLastPropertyType
PropertyInfo property = currentType.GetProperty(propertyName, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);```

**Comment by linmasaki** [comment]
In point 2, I recommend using the attribute [JsonPropertyName("Your Property Name")] to the class's property.  Like below code :point_down:

```csharp
public class Member
{
    [JsonPropertyName("email")]
    public string Email { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }
}
```

**Comment by linmasaki** [comment]
> Number 5 is actually this sadly https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client
> 

Could you provide a sample expression that you use to occur this issue?

**Comment by SoapyMan** [comment]
Thanks! Although I don't use JsonPropertyName (and others might do), it would be good to have that information on the repo readme too.

> > Number 5 is actually this sadly https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client
> 
> Could you provide a sample expression that you use to occur this issue?

It's all fine, resolved. Was my mistake to use non-db functions in Select operator before ToDataSourceResult

**Comment by linmasaki** [comment]
> It's all fine, resolved. Was my mistake to use non-db functions in Select operator before ToDataSourceResult

Ya, that's the point that I thought, cause I had encountered it before :joy:
