### ISSUE TITLE
Net Standard 2 Support

### ISSUE THREAD

**Issue by RudyWangCodes** [linmasaki/Kendo.DynamicLinqCore#2]
Is it support for net standard 2 application?

**Comment by linmasaki** [comment]
Sorry, I'm not sure whether it can work currently. But I will update it to net core 2 recently, thank you for your reported.

**Comment by RudyWangCodes** [comment]
thanks for the feed back

**Comment by RudyWangCodes** [comment]
hello,

I update this repo to net standards 2.0 project. This is my repo [link](https://github.com/RudyWangCodes/Kendo.DynamicLinq.Core)

I'm new in github, I'm not clearly sure how to make pull request to your repo and merge to your project.
I also added some additional filter string.

**Comment by linmasaki** [comment]
Hello, thank you for your enthusiasm helped^^.  I created a new repo and upgraded them to .Net Core 2.0 [here.](https://github.com/linmasaki/Kendo.DynamicLinqCore2) After I read your repo(Cause I found that their were some different when build, thus I thought it might be better to separate them).
You can also refer to [KendoUI.Core.Samples](https://github.com/VahidN/KendoUI.Core.Samples) by Vahid Nasiri. He offer a great complete demo for us!!! 

Note: I also upload a package to [nuget.org](https://www.nuget.org/packages/Kendo.DynamicLinqCore2/1.0.0), so you can search and add it by nuget tool console.

**Comment by RudyWangCodes** [comment]
Hello,

Thanks for the update and feedback. I used your library since net core 1 ^ ^v

**Comment by linmasaki** [comment]
The library now supports .NetStandard 1.6 and 2.0.
