### ISSUE TITLE
Aggregates broken ?

### ISSUE THREAD

**Issue by boisellea** [linmasaki/Kendo.DynamicLinqCore#5]
Hi again,

I'm trying to use aggregates with your code without success. 
Using : 

schema: {
                    model: {
                        fields: {
                            id: { type: "number" }
                        }
                    },
                    data: "Data",
                    total: "Total",
                    aggregates: "Aggregates",
                    groups: "Group",
                    errors: "Errors"
                },
                serverPaging: true,
                serverSorting: true,
                serverFiltering: true,
                serverAggregates: true,
                pageSize: 100,
                aggregate: [
                    { field: "id", aggregate: "count" }
                ]

My webservice returns nothing, no error but nothing is returned at all.
By the way, in the exemple you gave, I think your WebMethod definition should be 

[WebMethod]
public static DataSourceResult Products(int take, int skip, IEnumerable<Sort> sort, Filter filter, IEnumerable<Aggregator> **aggregate**, IEnumerable<Sort> group)

instead of 
[WebMethod]
public static DataSourceResult Products(int take, int skip, IEnumerable<Sort> sort, Filter filter, IEnumerable<Aggregator> **aggregates**, IEnumerable<Sort> group)

Thank you.
Arnaud

**Comment by linmasaki** [comment]
Ok, thank you for your question, I will test it later.  
If you don't mind, can you provide the version number of Kendo UI you use?  Thanks :blush:

**Comment by boisellea** [comment]
Sure : Kendo UI v2019.2.514
Thanks a lot again.

**Comment by linmasaki** [comment]
Hello, I just have updated this package, you can try it later.  

P.S. Notice the property "Group" of DataSourceResult has changed to "Groups". More details can see release notes.

**Comment by boisellea** [comment]
Hi,

I did not had the chance to test your new version until today :

Using Kendo.DynamicLinqCore.2.2.2 and Kendo UI v2019.3.1023.

Aggregate still does not work :

  var dataSource = new kendo.data.DataSource({
                transport: {
                    read: {
                        url: "https://xxx.com/Service.svc/GetCmds",
                        type: "POST",
                        dataType: "json",
                        contentType: "application/json"
                    },
                    parameterMap: function (data, type) {
                        if (type == "read") {
                            return JSON.stringify(data);
                        }
                    }
                },
                schema: {
                    model: {
                         fields: {
                            id_cmd: { type: "number" }
                        }
                    },
                    data: "Data",
                    total: "Total",
                    aggregates: "Aggregates"
                },
                serverPaging: true,
                serverSorting: true,
                serverFiltering: true,
                serverAggregates: true,
                pageSize: 25,
                aggregate: [{ field: "id_cmd", aggregate: "count" }]
            });

The request sent is :
{"take":25,"skip":0,"page":1,"pageSize":25,"aggregate":[{"field":"id_cmd","aggregate":"count"}]}

My webservice returns nothing, no error but nothing is returned at all. 

Thank you.
