### ISSUE TITLE
Default Sort (before query event)

### ISSUE THREAD

**Issue by luizfbicalho** [linmasaki/Kendo.DynamicLinqCore#7]
When sort is null or empty, Entity framework throws an exception.

Is there  a way to extend the DataSourceRequest to have an event Before query, this way I could set an event to change the default sort, or even  change filters

**Comment by linmasaki** [comment]
It worked fine after I set the sort to null or empty, but I just used Entity Framework Core.
If you want to use Entity Framework with this library, you can consider trying [Kendo.DynamicLinq](https://www.nuget.org/packages/Kendo.DynamicLinq/) at first.  

I think you can change the default sort, filters, aggregates before calling the method of ToDataSourceResult, does this help for you?

**Comment by luizfbicalho** [comment]
I had to put this code before calling the original Kendo.DynamicLinq.


`
public static class KendoExtensions
{

    private static Type[] types = new Type[] { typeof(decimal), typeof(decimal?), typeof(int), typeof(int?), typeof(long), typeof(long?), typeof(float), typeof(float?), typeof(double), typeof(double?) };
    public static void UpdateRequest<T>(this DataSourceRequest request)
    {
        UpdateFilter<T>(request.Filter);

        if (request.Filter != null && request.Filter.Filters != null && request.Filter.Filters.Count() == 0)
        {
            request.Filter = null;
        }
        if (request.Filter != null && request.Filter.Filters == null)
        {
            request.Filter = null;
        }

        if (request.Sort == null || request.Sort.Count() == 0)
        {
            var sort = new List<Sort>();
            sort.Add(new Sort() { Dir = "asc", Field = "Id" });
            request.Sort = sort;
        }
    }

    private static bool UpdateFilter<T>(Filter filter)
    {
        if (filter == null)
        {
            return true;
        }
        if (filter.Field != null)
        {
            var campo = filter.Field.Split('.');
            var val = filter.Value;
            var type = typeof(T);
            foreach (var c in campo)
            {
                type = type.GetProperty(c).PropertyType;
            }
            if (type.IsEnum)
            {
                val = val ?? "0";
                try
                {
                    var enumVal = Enum.Parse(type, val.ToString());
                    filter.Value = enumVal;
                }
                catch { }

            }
            else if (types.Contains(type))
            {
                return true;
            }
            else if (type != typeof(string))
            {
                if (filter.Value is DateTime)
                {

                    filter.Value = ((DateTime)filter.Value).Date;
                }
                else if (filter.Value is bool)
                {

                    filter.Value = ((bool)filter.Value);
                }
                else
                {
                    var converter = TypeDescriptor.GetConverter(type);
                    if (converter.IsValid(filter.Value))
                    {
                        filter.Value = converter.ConvertFromString(filter.Value.ToString());
                    }
                    else
                    {
                        return false;
                    }
                }

            }
        }
        if (filter.Filters == null)
        {
            return true;
        }
        foreach (var item in filter.Filters.ToList())
        {
            if (!UpdateFilter<T>(item))
            {
                filter.Filters = filter.Filters.Where(x => x != item);
            }
        }
        if (filter.Filters.Count() == 0)
        {
            filter.Filters = null;
        }
        return true;
    }
}
`

**Comment by linmasaki** [comment]
Sorry, I don't understand why you use that code you give before call ToDataSourceResult method, because in the extension method of ToDataSourceResult would already check incorrect parameters from filter and sort. 

I think in the extension method of ToDataSourceResult has already catch-all likely incorrect parameter come from the request of Kendo UI.

Could you give me a simple sample that can trigger the exception you said? Thanks!
